#!/usr/bin/env bash
# script that stores its PID, loops forever, and handles signals

# save current script PID into file
echo $$ > /tmp/myscript.pid

# function executed when SIGTERM is received
handle_sigterm() {
    echo "I hate the kill command"
}

# function executed when SIGINT is received
handle_sigint() {
    echo "Y U no love me?!"
}

# function executed when SIGQUIT or SIGTERM should terminate script
cleanup() {
    rm /tmp/myscript.pid
    exit
}

# trap signals
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap cleanup SIGQUIT

# infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
