#!/usr/bin/env bash
# Script that stores its PID, loops forever, and handles signals

echo $$ > /tmp/myscript.pid

handle_sigterm() {
    echo "I hate the kill command"
    rm /tmp/myscript.pid
    exit
}

handle_sigint() {
    echo "Y U no love me?!"
}

handle_sigquit() {
    rm /tmp/myscript.pid
    exit
}

trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
